This code shows the by example of dying neurons and the random experiment performed by Lu Lu et al

In [ ]:
import torch 
import torch.nn as nn
import numpy as np
import torch.nn.functional as F
import torch.optim as optim

tensor([-3.0094,  0.2165,  0.5130,  ..., -1.3341,  0.7234,  0.0397],
       dtype=torch.float64)
tensor([-0.6138,  0.8832,  0.5450,  ..., -0.3779, -0.4577,  0.1974],
       dtype=torch.float64)


In [ ]:

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.input_dim = 1
        output_dim = 1
        current_dim = 1
        hdim=2
        self.layers = nn.ModuleList()
        for h in range(9):
            self.layers.append(nn.Linear(current_dim, hdim))
            current_dim = hdim
        self.layers.append(nn.Linear(current_dim, output_dim))

    def forward(self, x):
        out=[]
        for layer in self.layers[:-1]:
            x = F.relu(layer(x))
            out.append(F.relu(self.layers[-1](x)))
        return out

In [ ]:
net=Net()
criterion = nn.MSELoss()
optimizer = optim.Adam(net.parameters(), lr=.01)

In [ ]:
X=np.random.uniform(-7**1/2, 7**1/2, 3000).astype(np.float32)
Xtrain=torch.tensor(X[:2100]).reshape(2100,1)
Xtest=torch.tensor(X[2101:]).reshape(899,1)
print(Xtrain.shape)
Y=np.sin(5*X).astype(np.float32)
Ytrain=torch.tensor(Y[:2100]).reshape(2100,1)
Ytest=torch.tensor(Y[2101:]).reshape(899,1)
for i in range(1000):
    train_loss = 0
    correct = 0
    total = 0
    test_loss = 0
    correct1 = 0
    total1 = 0
    acc=0
    for i in range(0,int(3000/64)): 
      optimizer.zero_grad()
      outputs = net(Xtrain[i:i+64])
      print(outputs[1])
      loss = criterion(outputs[-1],Ytrain[i:i+64])
      loss.backward()
      optimizer.step()

      train_loss += loss.item()
      predicted = outputs[-1]
      total += Ytrain[i:i+64].size(0)
      correct += predicted.eq(Ytrain[i:i+64]).sum().item()



    
    
      outputs = net(Xtest[i:i+64])
      print(outputs[1])
      loss = criterion(outputs[-1], Ytest[i:i+64])
      test_loss += loss.item()
      predicted = outputs[-1]
      total1 += Ytest[i:i+64].size(0)
      correct1 += predicted.eq(Ytest[i:i+64]).sum().item()
    print(correct1)

Streaming output truncated to the last 5000 lines.
        [0.0000],
        [0.0000],
        [0.0000],
        [0.0538],
        [0.0000],
        [0.0535],
        [0.0164]], grad_fn=<ReluBackward0>)
tensor([[0.0533],
        [0.0539],
        [0.0000],
        [0.0000],
        [0.0000],
        [0.0000],
        [0.0539],
        [0.0000],
        [0.0538],
        [0.0000],
        [0.0534],
        [0.0000],
        [0.0533],
        [0.0534],
        [0.0000],
        [0.0538],
        [0.0528],
        [0.0533],
        [0.0157],
        [0.0537],
        [0.0000],
        [0.0000],
        [0.0000],
        [0.0000],
        [0.0532],
        [0.0534],
        [0.0537],
        [0.0000],
        [0.0530],
        [0.0000],
        [0.0529],
        [0.0532],
        [0.0458],
        [0.0533],
        [0.0000],
        [0.0536],
        [0.0000],
        [0.0000],
        [0.0533],
        [0.0000],
        [0.0539],
        [0.0538],
        [0.0000],
        [0.0533],
     

This code shows the concept that leaky relu helps with the dying neuron problem

In [ ]:

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.input_dim = 1
        output_dim = 1
        current_dim = 1
        hdim=2
        self.layers = nn.ModuleList()
        for h in range(9):
            self.layers.append(nn.Linear(current_dim, hdim))
            current_dim = hdim
        self.layers.append(nn.Linear(current_dim, output_dim))

    def forward(self, x):
        out=[]
        for layer in self.layers[:-1]:
            x = F.leaky_relu(layer(x))
            out.append(F.leaky_relu(self.layers[-1](x)))
        return out

In [ ]:
net=Net()
criterion = nn.MSELoss()
optimizer = optim.Adam(net.parameters(), lr=.01)

In [ ]:
X=np.random.uniform(-7**1/2, 7**1/2, 3000).astype(np.float32)
Xtrain=torch.tensor(X[:2100]).reshape(2100,1)
Xtest=torch.tensor(X[2101:]).reshape(899,1)
print(Xtrain.shape)
Y=np.sin(5*X).astype(np.float32)
Ytrain=torch.tensor(Y[:2100]).reshape(2100,1)
Ytest=torch.tensor(Y[2101:]).reshape(899,1)
for i in range(1000):
    train_loss = 0
    correct = 0
    total = 0
    test_loss = 0
    correct1 = 0
    total1 = 0
    acc=0
    for i in range(0,int(3000/64)): 
      optimizer.zero_grad()
      outputs = net(Xtrain[i:i+64])
      print(outputs[1])
      loss = criterion(outputs[-1],Ytrain[i:i+64])
      loss.backward()
      optimizer.step()

      train_loss += loss.item()
      predicted = outputs[-1]
      total += Ytrain[i:i+64].size(0)
      correct += predicted.eq(Ytrain[i:i+64]).sum().item()



    
    
      outputs = net(Xtest[i:i+64])
      print(outputs[1])
      loss = criterion(outputs[-1], Ytest[i:i+64])
      test_loss += loss.item()
      predicted = outputs[-1]
      total1 += Ytest[i:i+64].size(0)
      correct1 += predicted.eq(Ytest[i:i+64]).sum().item()
    print(correct1)

Streaming output truncated to the last 5000 lines.
        [0.1069],
        [0.1031],
        [0.1068],
        [0.1068],
        [0.1030],
        [0.1069],
        [0.1045]], grad_fn=<LeakyReluBackward0>)
tensor([[0.1069],
        [0.1030],
        [0.1031],
        [0.1068],
        [0.1068],
        [0.1051],
        [0.1068],
        [0.1030],
        [0.1031],
        [0.1062],
        [0.1068],
        [0.1030],
        [0.1069],
        [0.1030],
        [0.1030],
        [0.1031],
        [0.1068],
        [0.1068],
        [0.1068],
        [0.1068],
        [0.1069],
        [0.1069],
        [0.1068],
        [0.1031],
        [0.1069],
        [0.1054],
        [0.1069],
        [0.1031],
        [0.1070],
        [0.1068],
        [0.1069],
        [0.1068],
        [0.1043],
        [0.1068],
        [0.1031],
        [0.1068],
        [0.1068],
        [0.1030],
        [0.1069],
        [0.1069],
        [0.1059],
        [0.1069],
        [0.1069],
        [0.1068],
